workflows:
  ios:
    name: Build iOS app
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS app
        script: |
          tns build ios --release
