workflows:
  ios:
    name: Build iOS app
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS app
        script: |
          npx react-native run-ios --configuration Release
