workflows:
  ios:
    name: Build iOS app
    scripts:
      - name: Install dependencies
        script: |
          npm install -g nativescript
          npm install
      - name: Build iOS app
        script: |
          mkdir -p /path/to/accessible/folder/App_Resources  # Создайте папку, если не существует
          tns build ios --release
